# Generated by Django 2.2.4 on 2019-08-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('header_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
